### ISSUE TITLE
Dupe with blocks that pickup items in the world 

### ISSUE THREAD

**Issue by Mattabase** [pcal43/quicksort#12]
If you place hoppers between the sorting chest and the chest items are sorting to the items will be picked up and placed in the chest duping them 

![image](https://user-images.githubusercontent.com/2126947/180067926-0fa011ea-971e-46a7-a246-dbe760429b11.png)

**Comment by pcal43** [comment]
Ah nice catch.  There should be a way to fix that.  Thanks for the report.

**Comment by pcal43** [comment]
should be fixed in 0.1.4
