### ISSUE TITLE
double chests are sometimes incorrectly recognized as full

### ISSUE THREAD

**Issue by pcal43** [pcal43/quicksort#5]
sorting sometimes gets skipped when the item is in the wrong half of the double inventory.

**Comment by pcal43** [comment]
fixed in 0.1.3

**Comment by RealSpyKitty** [comment]
![image](https://github.com/pcal43/quicksort/assets/49767994/3c587af7-0779-4ad7-9638-51a678c40bb6)
Having  issues while sorting like in the image above, if the items are in such or similar order like in the picture below then it works:
![image](https://github.com/pcal43/quicksort/assets/49767994/580f78af-4847-400b-9b76-cfc85e645f30)
